name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Gradle Cache
      uses: gradle/actions/setup-gradle@v3
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    - name: Build devRelease APK
      run: ./gradlew assembleDevRelease

    - name: Create Firebase Service Account File
      run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY_JSON }}' > $RUNNER_TEMP/google-credentials.json
      # IMPORTANT: Double-check the secret in GitHub settings NOW.
      # Make sure it contains the *entire* JSON content and nothing else.

    # --- Debugging Step 1: Verify file exists and has content ---
    - name: Check if Credentials File was Created
      run: |
        echo "Checking for credentials file at: $RUNNER_TEMP/google-credentials.json"
        ls -l $RUNNER_TEMP/google-credentials.json # List file details (check existence, size)
        echo "--- File Content Start ---"
        cat $RUNNER_TEMP/google-credentials.json || echo "ERROR: Cat failed, file likely doesn't exist or is empty."
        echo "--- File Content End ---"

    # --- Debugging Step 2: Verify the environment variable value ---
    - name: Echo Environment Variable Path
      run: echo "GOOGLE_APPLICATION_CREDENTIALS will be set to: $RUNNER_TEMP/google-credentials.json"

    - name: Upload devRelease APK to Firebase App Distribution
      # Add --stacktrace for more detailed Gradle error output
      run: ./gradlew appDistributionUploadDevRelease --stacktrace
      env:
        GOOGLE_APPLICATION_CREDENTIALS: $RUNNER_TEMP/google-credentials.json
        FIREBASE_APP_ID: "1:775510601297:android:564c49a5454afd3a609270"
