name: Android CI 



on: 

  push: 

    branches: [ "main" ] 

  pull_request: 

    branches: [ "main" ] 



jobs: 

  build: 



    runs-on: ubuntu-latest 



    steps: 

    - uses: actions/checkout@v4 

    - name: set up JDK 17 

      uses: actions/setup-java@v4 

      with: 

        java-version: '17' 

        distribution: 'temurin' 

        cache: gradle 



    - name: Setup Gradle Cache 

      uses: gradle/actions/setup-gradle@v3 

    - name: Grant execute permission for gradlew 

      run: chmod +x ./gradlew 

    - name: Build devRelease APK 

      run: ./gradlew assembleDevRelease 
   
    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.5.1
      with:
        appId: "1:775510601297:android:564c49a5454afd3a609270"
        #token: ${{secrets.FIREBASE_TOKEN}}   
        serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY_JSON }}      
        file: app/build/outputs/apk/debug/app-debug.apk
